#ifndef INC_4DVISUALIZATION_CONFIG_H
#define INC_4DVISUALIZATION_CONFIG_H

const int DEFAULT_WIDTH=800;
const int DEFAULT_HEIGHT=800;
const int DEFAULT_NEAR=5000;
const int DEFAULT_FAR=5000;

#endif //INC_4DVISUALIZATION_CONFIG_H
